server:
  port: 8080
  compression:
    enabled: true

mybatis:
  mapperLocations: classpath:mapper/mysql/*.xml
  typeAliasesPackage: kreadcn.homework.model

spring:
  servlet:
    multipart:
      max-file-size: 50MB
      max-request-size: 50MB
  task:
    scheduling:
      pool:
        size: 5

  datasource:
    url: jdbc:mysql://127.0.0.1:3306/homework?useUnicode=true&characterEncoding=utf-8&serverTimezone=GMT%2B8&useSSL=false&zeroDateTimeBehavior=convertToNull
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    show-sql: true
    database: mysql
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  mvc:
    pathmatch:
      matching-strategy: ANT_PATH_MATCHER

logging:
  level:
    root: INFO
    kreadcn.homework: debug
    kreadcn.homework.dao: debug
    org.springframework.web: INFO
    org.springframework.security: OFF
    org.springframework.security.oauth2: INFO

uploadPath: D:/stonered/redlib/homework/upload